// Default persisted state for a fresh local database.
// This mirrors the initial in-memory defaults in `app/store.ts`.

import type { Prisma } from "@prisma/client";

export type PersistedState = Prisma.JsonObject;

export function buildDefaultState(): PersistedState {
  const now = new Date();
  const currentYear = now.getFullYear();
  const financialYear = { startDate: `${currentYear}-01-01`, endDate: `${currentYear}-12-31` };
  const activeYearKey = `${financialYear.startDate}..${financialYear.endDate}`;

  return {
    // Dấu mốc reset/khởi tạo — đổi mỗi lần build default state (reset hoặc init DB mới).
    // Dùng để từ chối ghi đè từ client còn giữ dữ liệu cũ sau khi RESET (chống "phục hồi").
    stateResetMarker: `${now.getTime()}-${Math.random().toString(36).slice(2, 10)}`,
    activeTab: "dashboard",
    financialYear,
    financialYears: [financialYear],
    activeYearKey,
    yearDataByKey: {
      [activeYearKey]: {
        accountingPeriods: [],
        invoices: [],
        inventory: [],
        journalEntries: [],
        transactions: [],
        fundTransactions: [],
        accountingVouchers: [],
        cashFlowOpening: {},
        openingBalanceAccounts: [],
        openingBalanceDebts: [],
        openingBalanceRolloverMeta: null,
        citExpenseMeta: {},
        citLossRecords: [],
      },
    },
    deletedEntityTombstones: {},
    entityDeletionAuditLog: [],
    accountingPeriods: [],
    devices: [],
    invoices: [],
    inventory: [],
    bomDefinitions: [],
    journalEntries: [],
    transactions: [],
    fundTransactions: [],
    assets: [],
    accountingVouchers: [],
    openingBalanceAccounts: [],
    openingBalanceDebts: [],
    openingBalanceRolloverMeta: null,
    accounts: [
      { id: "acc_111", code: "111", name: "Tiền mặt", type: "Dư Nợ" },
      { id: "acc_1111", code: "1111", name: "Tiền Việt Nam", type: "Dư Nợ" },
      { id: "acc_1112", code: "1112", name: "Ngoại tệ", type: "Dư Nợ" },
      { id: "acc_112", code: "112", name: "Tiền gửi Ngân hàng", type: "Dư Nợ" },
      { id: "acc_1121", code: "1121", name: "Tiền Việt Nam", type: "Dư Nợ" },
      { id: "acc_1122", code: "1122", name: "Ngoại tệ", type: "Dư Nợ" },
      { id: "acc_121", code: "121", name: "Chứng khoán kinh doanh", type: "Dư Nợ" },
      { id: "acc_128", code: "128", name: "Đầu tư nắm giữ đến ngày đáo hạn", type: "Dư Nợ" },
      { id: "acc_1281", code: "1281", name: "Tiền gửi có kỳ hạn", type: "Dư Nợ" },
      { id: "acc_1288", code: "1288", name: "Các khoản đầu tư khác nắm giữ đến ngày đáo hạn", type: "Dư Nợ" },
      { id: "acc_131", code: "131", name: "Phải thu của Khách hàng", type: "Lưỡng tính" },
      { id: "acc_133", code: "133", name: "Thuế GTGT được khấu trừ", type: "Dư Nợ" },
      { id: "acc_1331", code: "1331", name: "Thuế GTGT được khấu trừ của hàng hoá, dịch vụ", type: "Dư Nợ" },
      { id: "acc_1332", code: "1332", name: "Thuế GTGT được khấu trừ TSCĐ", type: "Dư Nợ" },
      { id: "acc_136", code: "136", name: "Phải thu nội bộ", type: "Dư Nợ" },
      { id: "acc_1361", code: "1361", name: "Vốn kinh doanh ở đơn vị trực thuộc", type: "Dư Nợ" },
      { id: "acc_1368", code: "1368", name: "Phải thu nội bộ khác", type: "Dư Nợ" },
      { id: "acc_138", code: "138", name: "Phải thu khác", type: "Dư Nợ" },
      { id: "acc_1381", code: "1381", name: "Tài sản thiếu chờ xử lý", type: "Dư Nợ" },
      { id: "acc_1386", code: "1386", name: "Cầm cố, thế chấp, ký quỹ, ký cược", type: "Dư Nợ" },
      { id: "acc_1388", code: "1388", name: "Phải thu khác", type: "Dư Nợ" },
      { id: "acc_141", code: "141", name: "Tạm ứng", type: "Dư Nợ" },
      { id: "acc_151", code: "151", name: "Hàng mua đang đi đường", type: "Dư Nợ" },
      { id: "acc_152", code: "152", name: "Nguyên liệu, vật liệu", type: "Dư Nợ" },
      { id: "acc_153", code: "153", name: "Công cụ, dụng cụ", type: "Dư Nợ" },
      { id: "acc_154", code: "154", name: "Chi phí sản xuất, kinh doanh dở dang", type: "Dư Nợ" },
      { id: "acc_155", code: "155", name: "Thành phẩm", type: "Dư Nợ" },
      { id: "acc_156", code: "156", name: "Hàng hoá", type: "Dư Nợ" },
      { id: "acc_157", code: "157", name: "Hàng gửi đi bán", type: "Dư Nợ" },
      { id: "acc_211", code: "211", name: "Tài sản cố định", type: "Dư Nợ" },
      { id: "acc_2111", code: "2111", name: "TSCĐ Hữu hình", type: "Dư Nợ" },
      { id: "acc_2112", code: "2112", name: "TSCĐ thuê tài chính", type: "Dư Nợ" },
      { id: "acc_2113", code: "2113", name: "TSCĐ Vô hình", type: "Dư Nợ" },
      { id: "acc_214", code: "214", name: "Hao mòn tài sản cố định", type: "Dư Có" },
      { id: "acc_2141", code: "2141", name: "Hao mòn TSCĐ Hữu hình", type: "Dư Có" },
      { id: "acc_2142", code: "2142", name: "Hao mòn TSCĐ thuê tài chính", type: "Dư Có" },
      { id: "acc_2143", code: "2143", name: "Hao mòn TSCĐ vô hình", type: "Dư Có" },
      { id: "acc_2147", code: "2147", name: "Hao mòn Bất động sản đầu tư", type: "Dư Có" },
      { id: "acc_228", code: "228", name: "Đầu tư góp vốn vào đơn vị khác", type: "Dư Nợ" },
      { id: "acc_2281", code: "2281", name: "Đầu tư vào công ty liên doanh, liên kết", type: "Dư Nợ" },
      { id: "acc_2288", code: "2288", name: "Đầu tư khác", type: "Dư Nợ" },
      { id: "acc_229", code: "229", name: "Dự phòng tổn thất tài sản", type: "Dư Có" },
      { id: "acc_2291", code: "2291", name: "Dự phòng giảm giá chứng khoán kinh doanh", type: "Dư Có" },
      { id: "acc_2292", code: "2292", name: "Dự phòng tổn thất đầu tư vào đơn vị khác", type: "Dư Có" },
      { id: "acc_2293", code: "2293", name: "Dự phòng phải thu khó đòi", type: "Dư Có" },
      { id: "acc_2294", code: "2294", name: "Dự phòng giảm giá hàng tồn kho", type: "Dư Có" },
      { id: "acc_241", code: "241", name: "Xây dựng cơ bản dở dang", type: "Dư Nợ" },
      { id: "acc_2411", code: "2411", name: "Mua sắm TSCĐ", type: "Dư Nợ" },
      { id: "acc_2412", code: "2412", name: "Xây dựng cơ bản", type: "Dư Nợ" },
      { id: "acc_2413", code: "2413", name: "Sửa chữa lớn TSCĐ", type: "Dư Nợ" },
      { id: "acc_242", code: "242", name: "Chi phí trả trước", type: "Dư Nợ" },

      { id: "acc_331", code: "331", name: "Phải trả cho người bán", type: "Lưỡng tính" },
      { id: "acc_333", code: "333", name: "Thuế và các khoản phải nộp nhà nước", type: "Dư Có" },
      { id: "acc_3331", code: "3331", name: "Thuế GTGT phải nộp", type: "Dư Có" },
      { id: "acc_33311", code: "33311", name: "Thuế GTGT đầu ra", type: "Dư Có" },
      { id: "acc_33312", code: "33312", name: "Thuế GTGT hàng nhập khẩu", type: "Dư Có" },
      { id: "acc_3332", code: "3332", name: "Thuế tiêu thụ đặc biệt", type: "Dư Có" },
      { id: "acc_3333", code: "3333", name: "Thuế xuất, nhập khẩu", type: "Dư Có" },
      { id: "acc_3334", code: "3334", name: "Thuế thu nhập doanh nghiệp", type: "Dư Có" },
      { id: "acc_3335", code: "3335", name: "Thuế thu nhập cá nhân", type: "Dư Có" },
      { id: "acc_3336", code: "3336", name: "Thuế tài nguyên", type: "Dư Có" },
      { id: "acc_3337", code: "3337", name: "Thuế nhà đất, tiền thuê đất", type: "Dư Có" },
      { id: "acc_3338", code: "3338", name: "Nộp lệ phí môn bài", type: "Dư Có" },
      { id: "acc_33381", code: "33381", name: "Thuế bảo vệ môi trường", type: "Dư Có" },
      { id: "acc_33382", code: "33382", name: "Các loại thuế khác", type: "Dư Có" },
      { id: "acc_3339", code: "3339", name: "Phí, lệ phí và các khoản phải nộp khác", type: "Dư Có" },
      { id: "acc_334", code: "334", name: "Phải trả người lao động", type: "Dư Có" },
      { id: "acc_335", code: "335", name: "Chi phí phải trả", type: "Dư Có" },
      { id: "acc_336", code: "336", name: "Phải trả nội bộ", type: "Dư Có" },
      { id: "acc_3361", code: "3361", name: "Phải trả nội bộ về vốn kinh doanh", type: "Dư Có" },
      { id: "acc_3368", code: "3368", name: "Phải trả nội bộ khác", type: "Dư Có" },
      { id: "acc_338", code: "338", name: "Phải trả, phải nộp khác", type: "Lưỡng tính" },
      { id: "acc_3381", code: "3381", name: "Tài sản thừa chờ giải quyết", type: "Dư Có" },
      { id: "acc_3382", code: "3382", name: "Kinh phí công đoàn", type: "Dư Có" },
      { id: "acc_3383", code: "3383", name: "Bảo hiểm xã hội", type: "Dư Có" },
      { id: "acc_3384", code: "3384", name: "Bảo hiểm y tế", type: "Dư Có" },
      { id: "acc_3385", code: "3385", name: "Bảo hiểm thất nghiệp", type: "Dư Có" },
      { id: "acc_3386", code: "3386", name: "Nhận ký quỹ, ký cược", type: "Dư Có" },
      { id: "acc_3387", code: "3387", name: "Doanh thu chưa thực hiện", type: "Dư Có" },
      { id: "acc_3388", code: "3388", name: "Phải trả, phải nộp khác", type: "Lưỡng tính" },
      { id: "acc_341", code: "341", name: "Vay và nợ thuê tài chính", type: "Dư Có" },
      { id: "acc_3411", code: "3411", name: "Các khoản đi vay", type: "Dư Có" },
      { id: "acc_3412", code: "3412", name: "Nợ thuê tài chính", type: "Dư Có" },
      { id: "acc_352", code: "352", name: "Dự phòng phải trả", type: "Dư Có" },
      { id: "acc_3521", code: "3521", name: "Dự phòng bảo hành sản phẩm hàng hoá", type: "Dư Có" },
      { id: "acc_3522", code: "3522", name: "Dự phòng bảo hành công trình xây dựng", type: "Dư Có" },
      { id: "acc_3524", code: "3524", name: "Dự phòng phải trả khác", type: "Dư Có" },
      { id: "acc_353", code: "353", name: "Quỹ khen thưởng Phúc lợi", type: "Dư Có" },
      { id: "acc_3531", code: "3531", name: "Quỹ khen thưởng", type: "Dư Có" },
      { id: "acc_3532", code: "3532", name: "Quỹ phúc lợi", type: "Dư Có" },
      { id: "acc_3533", code: "3533", name: "Quỹ phúc lợi đã hình thành TSCĐ", type: "Dư Có" },
      { id: "acc_3534", code: "3534", name: "Quỹ thưởng ban quản lý điều hành công ty", type: "Dư Có" },
      { id: "acc_356", code: "356", name: "Quỹ phát triển khoa học và công nghệ", type: "Dư Có" },
      { id: "acc_3561", code: "3561", name: "Quỹ phát triển khoa học và công nghệ", type: "Dư Có" },
      { id: "acc_3562", code: "3562", name: "Quỹ phát triển khoa học và công nghệ đã hình thành TSCĐ", type: "Dư Có" },

      { id: "acc_4111", code: "4111", name: "Vốn đầu tư của chủ sở hữu", type: "Dư Có" },
      { id: "acc_4112", code: "4112", name: "Thặng dư vốn cổ phần", type: "Dư Có" },
      { id: "acc_4118", code: "4118", name: "Vốn khác", type: "Dư Có" },
      { id: "acc_413", code: "413", name: "Chênh lệch tỷ giá hối đoái", type: "Lưỡng tính" },
      { id: "acc_418", code: "418", name: "Các quỹ thuộc vốn chủ sở hữu", type: "Dư Có" },
      { id: "acc_419", code: "419", name: "Cổ phiếu quỹ", type: "Dư Nợ" },
      { id: "acc_421", code: "421", name: "Lợi nhuận sau thuế chưa phân phối", type: "Lưỡng tính" },
      { id: "acc_4211", code: "4211", name: "Lợi nhuận sau thuế chưa phân phối năm trước", type: "Lưỡng tính" },
      { id: "acc_4212", code: "4212", name: "Lợi nhuận sau thuế chưa phân phối năm nay", type: "Lưỡng tính" },

      { id: "acc_511", code: "511", name: "Doanh thu bán hàng và cung cấp dịch vụ", type: "Dư Có" },
      { id: "acc_5111", code: "5111", name: "Doanh thu bán hàng hoá", type: "Dư Có" },
      { id: "acc_5112", code: "5112", name: "Doanh thu bán thành phẩm", type: "Dư Có" },
      { id: "acc_5113", code: "5113", name: "Doanh thu cung cấp dịch vụ", type: "Dư Có" },
      { id: "acc_5118", code: "5118", name: "Doanh thu khác", type: "Dư Có" },
      { id: "acc_515", code: "515", name: "Doanh thu hoạt động tài chính", type: "Dư Có" },

      { id: "acc_611", code: "611", name: "Mua hàng", type: "Dư Nợ" },
      { id: "acc_631", code: "631", name: "Giá thành sản xuất", type: "Dư Nợ" },
      { id: "acc_632", code: "632", name: "Giá vốn hàng bán", type: "Dư Nợ" },
      { id: "acc_635", code: "635", name: "Chi phí tài chính", type: "Dư Nợ" },
      { id: "acc_642", code: "642", name: "Chi phí quản lý doanh nghiệp", type: "Dư Nợ" },
      { id: "acc_6421", code: "6421", name: "Chi phí bán hàng", type: "Dư Nợ" },
      { id: "acc_6422", code: "6422", name: "Chi phí quản lý doanh nghiệp", type: "Dư Nợ" },
      { id: "acc_6423", code: "6423", name: "Chi phí đồ dùng văn phòng", type: "Dư Nợ" },
      { id: "acc_6424", code: "6424", name: "Chi phí khấu hao TSCĐ", type: "Dư Nợ" },
      { id: "acc_6425", code: "6425", name: "Thuế, phí và lệ phí", type: "Dư Nợ" },
      { id: "acc_6426", code: "6426", name: "Chi phí dự phòng", type: "Dư Nợ" },
      { id: "acc_6427", code: "6427", name: "Chi phí dịch vụ mua ngoài", type: "Dư Nợ" },
      { id: "acc_6428", code: "6428", name: "Chi phí bằng tiền khác", type: "Dư Nợ" },

      { id: "acc_711", code: "711", name: "Thu nhập khác", type: "Dư Có" },

      { id: "acc_811", code: "811", name: "Chi phí khác", type: "Dư Nợ" },
      { id: "acc_821", code: "821", name: "Chi phí thuế thu nhập doanh nghiệp", type: "Dư Nợ" },

      { id: "acc_911", code: "911", name: "Xác định kết quả kinh doanh", type: "Lưỡng tính" }
    ],
    customers: [],
    suppliers: [],
    employees: [],
    warehouses: [],
    expenseCategories: [],
    taxRates: [
      { id: "1", code: "VAT0", name: "VAT 0%", rate: 0 },
      { id: "2", code: "VAT8", name: "VAT 8%", rate: 8 },
      { id: "3", code: "VAT10", name: "VAT 10%", rate: 10 }
    ],
    paymentMethods: [
      { id: "1", code: "TM", name: "Tiền mặt" },
      { id: "2", code: "CK", name: "Chuyển khoản" }
    ],
    // B03-DNN: values for the "Số đầu năm" column by code (e.g. { "01": 1000000, "02": -500000, ... })
    cashFlowOpening: {},
    citExpenseMeta: {},
    citLossRecords: [],
    systemConfig: {
      initializationDate: new Date().toISOString(),
      openingBalanceLock: "OPEN",
      accountingRegime: {
        standard: "TT133",
        effectiveFrom: financialYear.startDate,
      },
    },
    companyInfo: {
      name: "Công ty TNHH TMDV và Công nghệ Victory",
      taxCode: "0109238339",
      phone: "0922248868",
      address: "Số 5, tổ 4, phường Phúc Lợi, TP Hà Nội, Việt Nam",
      city: "Hà Nội",
      country: "Việt Nam",
      email: "Hanoivictory@gmail.com"
    },
    modals: {},
    /** Gợi ý phiếu kho (NCC/KH, HĐ) — đồng bộ SQLite, không phụ thuộc localStorage. */
    warehouseFormHints: {},
    /** Gợi ý tên KH / NCC / đối tượng chứng từ (đã nhập) — đồng bộ SQLite. */
    partnerNameHistory: { customer: [], supplier: [], contact: [] },
    /** Bản sao danh mục dự phòng (khi server rỗng có thể khôi phục) — đồng bộ SQLite. */
    catalogBackupSnapshot: null,
    /** Hotel PMS — phòng, booking, kho PMS, chi phí (đồng bộ đa máy qua AppState). */
    hotelPms: null,
  } as PersistedState;
}

